import { Card, CardContent, CardHeader, CardTitle } from "~/components/ui/Card";
import { Scale, CheckCircle2, AlertTriangle } from "lucide-react";

interface LegalAnalysisTabProps {
  caseData: any;
}

export function LegalAnalysisTab({ caseData }: LegalAnalysisTabProps) {
  const analysisResults = (caseData.analysisResults as any) || {};
  const causesOfAction = analysisResults.causesOfAction || (caseData.generatedCausesOfAction as any[]) || [];

  if (causesOfAction.length === 0) {
    return (
      <Card>
        <CardContent className="py-12 text-center">
          <Scale className="mx-auto h-12 w-12 text-gray-400" />
          <p className="mt-4 text-gray-600">No causes of action identified</p>
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="space-y-6">
      {/* AI Disclaimer */}
      <div className="rounded-xl border border-amber-200 bg-amber-50 p-4">
        <p className="text-sm text-amber-800 leading-relaxed">
          <strong>Important:</strong> This legal analysis is generated by AI and has not been reviewed by an attorney. 
          Claim strength percentages are estimates based on the information provided, not legal opinions. 
          This analysis is intended to help organize your case for attorney review — it is not a substitute for professional legal counsel.
        </p>
      </div>

      <div className="text-center mb-6">
        <h2 className="text-2xl font-bold text-gray-900">Identified Legal Claims</h2>
        <p className="mt-2 text-gray-600">
          {causesOfAction.length} potential {causesOfAction.length === 1 ? "claim" : "claims"} identified
        </p>
      </div>

      {causesOfAction.map((claim: any, index: number) => (
        <Card key={index} className="border-l-4 border-l-primary-500">
          <CardHeader>
            <div className="flex items-start justify-between gap-4">
              <CardTitle className="text-xl">{claim.name}</CardTitle>
              <div className="flex items-center gap-2">
                <span className="text-2xl font-bold text-primary-600">
                  {Math.round(claim.strength)}%
                </span>
              </div>
            </div>
            {/* Strength bar */}
            <div className="mt-3">
              <div className="flex items-center justify-between text-sm mb-1">
                <span className="text-gray-600">Claim Strength</span>
              </div>
              <div className="h-3 overflow-hidden rounded-full bg-gray-200">
                <div
                  className={`h-full transition-all ${
                    claim.strength >= 70
                      ? "bg-green-500"
                      : claim.strength >= 40
                      ? "bg-yellow-500"
                      : "bg-red-500"
                  }`}
                  style={{ width: `${claim.strength}%` }}
                />
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {/* Required Elements with Evidence Status */}
              {claim.elements && claim.elements.length > 0 && (
                <div>
                  <h4 className="flex items-center gap-2 font-semibold text-gray-900 mb-3">
                    <CheckCircle2 className="h-5 w-5 text-green-600" />
                    Required Legal Elements
                  </h4>
                  <div className="space-y-3">
                    {claim.elements.map((el: any, idx: number) => {
                      const element = typeof el === 'string' ? { element: el, status: 'UNKNOWN', evidence: '' } : el;
                      const statusColors: Record<string, string> = {
                        SUPPORTED: 'bg-green-100 text-green-800 border-green-200',
                        PARTIALLY_SUPPORTED: 'bg-yellow-100 text-yellow-800 border-yellow-200',
                        UNSUPPORTED: 'bg-red-100 text-red-800 border-red-200',
                        UNKNOWN: 'bg-gray-100 text-gray-800 border-gray-200',
                      };
                      const statusLabels: Record<string, string> = {
                        SUPPORTED: '✓ Supported',
                        PARTIALLY_SUPPORTED: '◐ Partial',
                        UNSUPPORTED: '✗ Unsupported',
                        UNKNOWN: '? Unknown',
                      };
                      return (
                        <div key={idx} className="rounded-lg border border-gray-200 p-3">
                          <div className="flex items-start justify-between gap-3">
                            <span className="text-sm font-medium text-gray-900">{element.element}</span>
                            <span className={`inline-flex items-center rounded-full border px-2 py-0.5 text-xs font-medium whitespace-nowrap ${statusColors[element.status] || statusColors.UNKNOWN}`}>
                              {statusLabels[element.status] || '? Unknown'}
                            </span>
                          </div>
                          {element.evidence && (
                            <p className="mt-2 text-sm text-gray-600">{element.evidence}</p>
                          )}
                        </div>
                      );
                    })}
                  </div>
                </div>
              )}

              {/* Factual Support */}
              <div>
                <h4 className="font-semibold text-gray-900 mb-2">
                  Factual Support
                </h4>
                <div className="rounded-lg bg-blue-50 p-3 border border-blue-200">
                  <p className="text-sm text-blue-800">
                    Based on the evidence and information provided in your case intake and uploaded documents.
                  </p>
                </div>
              </div>

              {/* Weaknesses */}
              {claim.weaknesses && claim.weaknesses.length > 0 && (
                <div>
                  <h4 className="flex items-center gap-2 font-semibold text-gray-900 mb-2">
                    <AlertTriangle className="h-5 w-5 text-orange-600" />
                    Potential Weaknesses
                  </h4>
                  <ul className="space-y-2">
                    {claim.weaknesses.map((weakness: string, idx: number) => (
                      <li key={idx} className="flex items-start gap-2 text-sm">
                        <span className="text-orange-600 mt-0.5">⚠</span>
                        <span className="text-gray-700">{weakness}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          </CardContent>
        </Card>
      ))}
    </div>
  );
}
