import { Card, CardContent, CardHeader, CardTitle } from "~/components/ui/Card";
import Markdown from "markdown-to-jsx";

interface ProAnalysisViewProps {
  proResults: {
    executiveSummary: string;
    adversarialLiability: string;
    solAndThresholdDefenses: string;
    damagesMemo: string;
    riskRegister: string;
    recommendations: string;
    generatedAt: string;
  };
}

const SECTIONS = [
  { key: "executiveSummary", title: "Executive Summary", icon: "📋" },
  { key: "adversarialLiability", title: "Liability Analysis (Adversarial)", icon: "⚖️" },
  { key: "solAndThresholdDefenses", title: "SOL & Threshold Defenses", icon: "⏰" },
  { key: "damagesMemo", title: "Damages & Fee Analysis", icon: "💰" },
  { key: "riskRegister", title: "Risk Register", icon: "🚩" },
  { key: "recommendations", title: "Recommendations", icon: "✅" },
] as const;

export function ProAnalysisView({ proResults }: ProAnalysisViewProps) {
  return (
    <div className="space-y-6">
      {/* Disclaimer */}
      <div className="rounded-xl border border-amber-200 bg-amber-50 p-4">
        <p className="text-sm text-amber-800 leading-relaxed">
          <strong>AI-Generated Analysis:</strong> This attorney-ready packet was generated by AI
          and has not been reviewed by a licensed attorney. It is designed to organize your case
          for professional review — not to replace legal counsel. All assessments are estimates
          based on the information you provided.
        </p>
      </div>

      <p className="text-sm text-gray-500">
        Generated {new Date(proResults.generatedAt).toLocaleDateString()} at{" "}
        {new Date(proResults.generatedAt).toLocaleTimeString()}
      </p>

      {SECTIONS.map(({ key, title, icon }) => {
        const content = proResults[key as keyof typeof proResults];
        if (!content || typeof content !== "string") return null;

        return (
          <Card key={key}>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <span>{icon}</span>
                {title}
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="prose prose-sm max-w-none prose-headings:text-gray-900 prose-p:text-gray-700 prose-strong:text-gray-900 prose-li:text-gray-700">
                <Markdown>{content}</Markdown>
              </div>
            </CardContent>
          </Card>
        );
      })}
    </div>
  );
}
